server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.onlineclothingstore: DEBUG

---

#for test
spring:
  config:
    activate:
      on-profile: test

app:
  clients-service:
    host: localhost
    port: 7001
  employees-service:
    host: localhost
    port: 7002
  inventory-service:
    host: localhost
    port: 7003
  sales-service:
    host: localhost
    port: 7004


---
# for docker

spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

#spring.datasource.hikari.initializationFailTimeout: 60000

app:
  clients-service:
    host: clients-service
    port: 8080
  employees-service:
    host: employees-service
    port: 8080
  inventory-service:
    host: inventory-service
    port: 8080
  sales-service:
    host: sales-service
    port: 8080
